ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=☁️ 代理选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
ruleset=☁️ 代理选择,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
ruleset=☁️ 代理选择,[]DOMAIN-SUFFIX,services.googleapis.cn
ruleset=DIRECT,[]GEOIP,CN
ruleset=🎈 其余流量,[]FINAL

custom_proxy_group=☁️ 代理选择`select`[]⚡ 自动选择`[]🔮 负载均衡`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇲 美国节点`
custom_proxy_group=✏️ 手动选择`select`.*
custom_proxy_group=🇭🇰 香港节点`url-test`(🇭🇰)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇨🇳 台湾节点`url-test`(🇨🇳)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 狮城节点`url-test`(🇸🇬)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本节点`url-test`(🇯🇵)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇰🇷 韩国节点`url-test`(🇰🇷)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 美国节点`url-test`(🇺🇲)`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=⚡ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300
custom_proxy_group=🔮 负载均衡`load-balance`(🇭🇰)`http://www.gstatic.com/generate_204`300,,50

enable_rule_generator=true
overwrite_original_rules=true
add_emoji=true
remove_old_emoji=true
skip_cert_verify_flag=true
clash_use_new_field_name=true
write_managed_config=false
udp_flag=false

exclude_remarks=(续费|重置|推广|佣金|IPV6接入|TG群|到期|Update|Traffic|更新订阅|更新一次订阅|不一定|勒索|通告|均为二手倒卖|重大漏洞|公告|已恢复|炸了|Expire|时间|Panel|用户群|学术|登录|面板|计划|全局代理)

emoji=(Channel|Website),⚫︎
emoji=(新加坡|[狮獅]城|新坡|广新|浙新|杨新|安新|海新|SG|sg|SINGAPORE|Singapore),🇸🇬
emoji=(香港|亚服游戏|亚服防失联|中港|深港IEPL|深港专线 ⁴ˣ|广港|莞港|海港|苏港|湘港|杨港|安港|永久虚通路连接|港鱼蛋粉|港鸡蛋仔|AnyPath®|HK|hk|HONG KONG|Hong Kong|HONGKONG|Hongkong|HongKong),🇭🇰
emoji=(台湾|台灣|台北|台中|新北|彰化|深港专线转台湾|冀台|沪台|浙台|深台|湘台|珠台|苏台|闽台|广台|回国|Taipei|Kaohsiung|TW|TPE|Taiwan|TAIPEI|TAIWAN|Tai Wan|Tai wan),🇨🇳
emoji=(美[国國]|广美|美西|华盛顿|波特兰|达拉斯|俄勒冈|凤凰城|菲尼克斯|费利蒙|弗里蒙特|硅谷|旧金山|弗吉尼亚|拉斯维加斯|洛杉|圣何塞|圣荷西|圣塔?克拉拉|西雅图|芝加哥|哥伦布|纽约|阿什本|丹佛|加利福尼亚|us|UNITED STATES|SEA|EWR|Newark|SJC|LAX|CMH|SANJOSE|Washington|Portland|Dallas|Oregon|Phoenix|Fremont|Valley|Francisco|Vegas|Los[^a-z]*Angeles|San[^a-z]*Jose|Santa[^a-z]*Clara|Seattle|Chicago|Columbus|York|America|Ashburn|US|UNITEDSTATES|United States),🇺🇲
emoji=(日本|日-本|东京|大阪|埼玉|名古屋|沪日|日服|广日|杭日|京日|JP|jp|TOKYO|Tokyo|Osaka|Fukuoka|Nagoya|JAPAN|KIX|Saitama|Japan),🇯🇵
emoji=(安道尔|Andorra),🇦🇩
emoji=(阿联酋|迪拜|阿布扎比|阿拉伯联合酋长国|Dubai|AE|United Arab Emirates),🇦🇪
emoji=(阿富汗|Afghanistan),🇦🇫
emoji=(阿尔巴尼亚|Albania),🇦🇱
emoji=(亚美尼亚|Armenia),🇦🇲
emoji=(安哥拉|Angola),🇦🇴
emoji=(阿根廷|Argentina|ARG|AR),🇦🇷
emoji=(奥地利|奧地利|AT|Austria),🇦🇹
emoji=(澳大利亚|澳洲|悉尼|墨尔本|AU|Australia|Sydney),🇦🇺
emoji=(阿鲁巴|Aruba),🇦🇼
emoji=(阿塞拜疆|Azerbaijan),🇦🇿
emoji=(波黑|波斯尼亚和黑塞哥维那|Herzegovina),🇧🇦
emoji=(巴巴多斯|Barbados),🇧🇧
emoji=(孟加拉|Bangladesh),🇧🇩
emoji=(比利时|比利時|BE|Belgium),🇧🇪
emoji=(保加利亚|Bulgaria),🇧🇬
emoji=(巴林|Bahrain),🇧🇭
emoji=(百慕大|Bermuda),🇧🇲
emoji=(文莱|Brunei),🇧🇳
emoji=(玻利维亚|Bolivia),🇧🇴
emoji=(巴西|圣保罗|São Paulo|S?o Paulo|BR|Brazil),🇧🇷
emoji=(巴哈马|Bahamas),🇧🇸
emoji=(不丹|Bhutan),🇧🇹
emoji=(白俄罗斯|Belarus),🇧🇾
emoji=(伯利兹|Bolize),🇧🇿
emoji=(加拿大|蒙特利尔|温哥华|多伦多|Montréal|Vancouver|Toronto|YYZ|CA|Canada),🇨🇦
emoji=(瑞士|Switzerland),🇨🇭
emoji=(智利|Santiago|Chile),🇨🇱
emoji=(哥伦比亚|圣地亚哥|Colombia),🇨🇴
emoji=(哥斯达黎加|Costa Rica),🇨🇷
emoji=(库拉索|Curacao),🇨🇼
emoji=(塞浦路斯|Cyprus),🇨🇾
emoji=(捷克|布拉格|Czech),🇨🇿
emoji=(德国|法兰克福|京德游戏|柏林|FI|Frankfurt|DE|Germany),🇩🇪
emoji=(吉布提|Djibouti),🇩🇯
emoji=(丹麦|哥本哈根|DNK|DK|Danmark|Denmark),🇩🇰
emoji=(阿尔及利亚|Algeria),🇩🇿
emoji=(厄瓜多尔|Ecuador),🇪🇨
emoji=(爱沙尼亚|Estonia),🇪🇪
emoji=(埃及|开罗|EGP|Egypt),🇪🇬
emoji=(西班牙|马德里|ESP|Madrid|Spain),🇪🇸
emoji=(芬兰|芬蘭|Finland),🇫🇮
emoji=(法国|巴黎|Marseille|CDG|Paris|FR|France),🇫🇷
emoji=(英国|英|伦敦|UK|GBR|LHR|London|England|Britain|Kingdom),🇬🇧
emoji=(格鲁吉亚|Georgia),🇬🇪
emoji=(加纳|Ghana),🇬🇭
emoji=(格陵兰|GRL|Greenland),🇬🇱
emoji=(希腊|希臘|雅典|GRC|Greece),🇬🇷
emoji=(危地马拉|Guatemala),🇬🇹
emoji=(克罗地亚|Croatia),🇭🇷
emoji=(匈牙利|Hungary),🇭🇺
emoji=(印度尼西亚|印尼|雅加达|IDN|Indonesia),🇮🇩
emoji=(爱尔兰|愛爾蘭|都柏林|IE|Ireland),🇮🇪
emoji=(以色列|耶路撒冷|ISL|ISR|IL|Israel),🇮🇱
emoji=(马恩岛|Isle of Man),🇮🇲
emoji=(伊朗|Iran),🇮🇷
emoji=(冰岛|冰島|雷克雅未克|Iceland),🇮🇸
emoji=(意大利|意|罗马|米兰|Italy),🇮🇹
emoji=(印度|孟买|新德里|加尔各答|Mumbai|IN|IND|India),🇮🇳
emoji=(泽西岛|Jersey),🇯🇪
emoji=(约旦|Jordan),🇯🇴
emoji=(肯尼亚|Kenya),🇰🇪
emoji=(吉尔吉斯斯坦|Kyrgyzstan),🇰🇬
emoji=(柬埔寨|金边|Kampuchea|Cambodia),🇰🇭
emoji=(开曼群岛|Cayman Islands),🇰🇾
emoji=(科索沃|Kosovo),🇽🇰
emoji=(韩国|韩|韓|首尔|KR|KOR|kr|CHUNCHEON|春川|大版|Seoul|ICN|Chuncheon|Korea),🇰🇷
emoji=(哈萨克斯坦|哈薩克斯坦|努尔苏丹|KZ|Kazakhstan),🇰🇿
emoji=(老挝|Laos),🇱🇦
emoji=(列支敦士登|Liechtenste),🇱🇮
emoji=(斯里兰卡|Sri Lanka),🇱🇰
emoji=(立陶宛|Lithuania),🇱🇹
emoji=(卢森堡|盧森堡|LU FranTech|LU|Luxembourg),🇱🇺
emoji=(拉脱维亚|Latvija|Latvia),🇱🇻
emoji=(利比亚|Libya),🇱🇾
emoji=(澳门|澳門|MAC|MTel|MO|Macao|Macau),🇲🇴
emoji=(摩洛哥|Morocco),🇲🇦
emoji=(摩纳哥|Monaco),🇲🇨
emoji=(摩尔多瓦|Moldova),🇲🇩
emoji=(黑山|Montenegro),🇲🇪
emoji=(北马其顿|Macedonia),🇲🇰
emoji=(缅甸|Myanmar|Burma),🇲🇲
emoji=(蒙古|Mongolia),🇲🇳
emoji=(马耳他|Malta),🇲🇹
emoji=(毛里求斯|Mauritius),🇲🇺
emoji=(墨西哥|MEX|Mexico),🇲🇽
emoji=(马来西亚|马来|大马|MYS|Malaysia),🇲🇾
emoji=(尼日利亚|NG|Nigeria),🇳🇬
emoji=(荷兰|阿姆斯特丹|NLD|AMS|NL|SC|Netherlands),🇳🇱
emoji=(挪威|Norway),🇳🇴
emoji=(尼泊尔|NP|Nepal),🇳🇵
emoji=(新西兰|新西蘭|NZL|NZ|New Zealand),🇳🇿
emoji=(阿曼|Oman),🇴🇲
emoji=(巴拿马|PAN|Panama),🇵🇦
emoji=(秘鲁|Peru),🇵🇪
emoji=(菲律宾|马尼拉|PHL|Philippines),🇵🇭
emoji=(巴基斯坦|Pakistan),🇵🇰
emoji=(波兰|波蘭|POL|PL|Poland),🇵🇱
emoji=(波多黎各|Puerto),🇵🇷
emoji=(葡萄牙|Portugal),🇵🇹
emoji=(巴拉圭|Paraguay),🇵🇾
emoji=(卡塔尔|Qatar),🇶🇦
emoji=(留尼汪|Reunio),🇷🇪
emoji=(罗马尼亚|Romania),🇷🇴
emoji=(塞尔维亚|Serbia),🇷🇸
emoji=(俄罗斯|伯力|莫斯科|圣彼得堡|西伯利亚|毛子|Moscow|RU|Russia),🇷🇺
emoji=(卢旺达|Rwanda),🇷🇼
emoji=(沙特阿拉伯|沙特|SA|Saudi Arabia),🇸🇦
emoji=(瑞典|SE|Stockholm|Sweden),🇸🇪
emoji=(斯洛文尼亚|Slovenia),🇸🇮
emoji=(斯洛伐克|Slovensko|Slovakia),🇸🇰
emoji=(朝鲜|KP|DPK|North Korea),🇰🇵
emoji=(泰国|曼谷|泰國|THA|TH|Thailand|TH 01),🇹🇭
emoji=(突尼斯|Tunisia),🇹🇳
emoji=(土耳其|伊斯坦布尔|TUR|Turkey|TR),🇹🇷
emoji=(乌兹别克|Uzbekistan),🇺🇿
emoji=(梵蒂冈|VAT|Vatican),🇻🇦
emoji=(委内瑞拉|Venezuela),🇻🇪
emoji=(越南|VN|Vietnam),🇻🇳
emoji=(乌克兰|基辅|Ukraine),🇺🇦
emoji=(乌拉圭|Uruguay),🇺🇾
emoji=(英属维尔京群岛|British Virgin Islands),🇻🇬
emoji=(美属维尔京群岛|U.S. Virgin Islands),🇻🇮
emoji=(也门|Yemen),🇾🇪
emoji=(南非|Johannesburg|ZA|South Africa),🇿🇦
emoji=(南极|Antarctica|AQ|ATA),🇦🇶
emoji=(古巴|CUB|Cuba),🇨🇺
emoji=(马尔代夫),🇲🇻
emoji=(关岛),🇬🇺
emoji=(斐济),🇫🇯
emoji=(巴勒斯坦),🇵🇸
emoji=(东帝汶),🇹🇱
emoji=(黎巴嫩),🇱🇧
emoji=(伊拉克),🇮🇶
emoji=(叙利亚),🇸🇾
emoji=(科威特|KW),🇰🇼
emoji=(土库曼斯坦),🇹🇲
emoji=(汤加),🇹🇴
emoji=(所罗门群岛),🇸🇧
emoji=(巴布亚新几内亚),🇵🇬
emoji=(直布罗陀),🇬🇮
emoji=(圣马力诺),🇸🇲
emoji=(法罗群岛),🇫🇴
emoji=(奥兰群岛),🇦🇽
emoji=(海地),🇭🇹
emoji=(牙买加),🇯🇲
emoji=(苏里南),🇸🇷
emoji=(法属圭亚那),🇬🇫
emoji=(特立尼达和多巴哥),🇹🇹
emoji=(洪都拉斯),🇭🇳
emoji=(尼加拉瓜),🇳🇮
emoji=(多米尼克),🇩🇲
emoji=(多米尼加),🇩🇴
emoji=(多哥),🇹🇬
emoji=(贝宁),🇧🇯
emoji=(马里),🇲🇱
emoji=(刚果),🇨🇩
emoji=(佛得角),🇨🇻
emoji=(喀麦隆),🇨🇲
emoji=(莫桑比克),🇲🇿
emoji=(科特迪瓦),🇨🇮
emoji=(斯威士兰),🇸🇿
emoji=(坦桑尼亚),🇹🇿
emoji=(欧洲|EU),🇪🇺
